"""delete Role.user_id

Revision ID: 24b4d089b22b
Revises: af4e914083c0
Create Date: 2025-11-25 19:35:07.507408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b4d089b22b'
down_revision: Union[str, Sequence[str], None] = 'af4e914083c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roles_user_id_fkey'), 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('roles_user_id_fkey'), 'roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
