"""add table shop, shop version column reason

Revision ID: ddb58ce3c722
Revises: be282742d349
Create Date: 2026-09-08 13:58:22.212532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb58ce3c722'
down_revision: Union[str, Sequence[str], None] = 'be282742d349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_versions', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'reason')
    op.drop_column('shop_versions', 'reason')
    # ### end Alembic commands ###
