"""columns review null

Revision ID: 3978c3f0ce1c
Revises: ddb58ce3c722
Create Date: 2026-09-08 17:25:45.699117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3978c3f0ce1c'
down_revision: Union[str, Sequence[str], None] = 'ddb58ce3c722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_versions', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shop_versions', 'reviewed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shops', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shops', 'reviewed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'reviewed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shops', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('shop_versions', 'reviewed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shop_versions', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
